-- What the sigma?

return {
	["Common"] = "Very common thing",
	["Uncommon"] = "Very uncommon thing",
	["Good"] = "Very good thing",
	["Natural"] = "What a natural thing",
	["Rare"] = "Rare thing",
	["Divinus"] = "Holy thing",
	["Crystallized"] = "Shining thing",
	["Rage"] = "Flame of emotions",
	["Topaz"] = "Gem of a brown hue",
	["Ruby"] = "Gem of a red hue",
	["Emerald"] = "Gem of a green hue",
	["Gilded"] = "That\'s a shiny one!",
	["Jackpot"] = "That\226\128\153s such a tremendous prize!",
	["Sapphire"] = "Gem of an azure hue",
	["Glock"] = "What do you mean by <font color=\"rgb(115,208,255)\"><b>Aura</b></font>? It\'s literally just a <b><font color=\"rgb(63,63,63)\">Glock-17</font></b>!",
	["Lunar"] = "It was made with <font color=\"rgb(97,87,153)\">Moonlight</font> by an <font color=\"rgb(161,145,255)\">Unknown being</font> on a quiet night.",
	["Solar"] = "It was made with <font color=\"rgb(239,196,90)\">Sunshine</font> by an <font color=\"rgb(241,188,75)\">Unknown being</font> on a bright day.",
	["Bleeding"] = "Endlessly oozing <font color=\"rgb(172,21,40)\"><b>blood</b>...</font> \nHey, you sure you alright?",
	[":Flushed:"] = "<font size=\"30\"> \240\159\152\179</font>",
	["Undead"] = "<font color=\"rgb(38,169,10)\"><b>failed to die</b></font>....",
	["Aquatic"] = "It represents the flow of <font color=\"rgb(24,134,255)\">water</font>",
	["Starlight"] = "This starlight with <b>mysterious <font color=\"rgb(170,236,250)\">powers</font></b> 0used will follow you persistently, illuminating the path",
	["Nautilus"] = "A small shout resounding from the depths of the <font color=\"rgb(5,2,160)\"><b>abyss</b></font>..",
	["Exotic"] = "Nobody knows where it <font color=\"rgb(16,234,146)\"><b>originates</b></font> from, and how <font color=\"rgb(255,21,21)\"><b>old</b></font> it is.",
	["Jade"] = "This, is the name of a legendary man who approaches ones lost in the vast forest and gives directions. He is kind, and knows the forest better than anyone else. But one day, he stopped showing himself to people. Where did he go?",
	["Comet"] = "People believe that it has the capabilities to make <font color=\"rgb(90,234,225)\"><b>wishes</b></font> come <b>true</b>.",
	["BOUNDED"] = "It\'s too dangerous. Although it was sealed by an <b><font color=\"rgb(192,228,93)\">Ancient Power</font></b> hundreds of thousands of years ago, its consciousness appears to be <font color=\"rgb(228,0,0)\">alive</font>",
	["Stormal"] = "An enormous <font color=\"rgb(113,113,113)\"><b>storm</b></font> raging around you.",
	["Permafrost"] = "You can find it in <font color=\"rgb(148,234,246)\">cold lands</font> throughout the year, unaffected by the seasons.",
	["Celestial"] = "A holy being that descended from <font color=\"rgb(226,246,160)\">heaven</font>?",
	["Twilight"] = "A jewel that shines brightly once every thousand years in the deepest part of the forest. No one has ever seen how bright that light is. According to rumors, the moon gives gifts to those who look at the gem with a pure heart without any evil...",
	["Kyawthuite"] = "Long, long ago, there was a \'boy\' who stayed alone in the empty space of a deep cave. He is still waiting for the day when he can sit on the moon together with the girl who suddently left when he was young , somewhere in the forest and talk again, <font color=\"rgb(157, 133, 255)\">once in a thousand years, in the deepest part of the forest...</font>",
	["Arcane"] = "A <font color=\"rgb(88,210,238)\">spell</font> found in the ruins of an ancient civilization \nthis swaying silhouette that seems to possess its own consciousness has a record of completely erasing one civilization from history.",
	["Undefined"] = "<i><font color=\"rgb(23,23,23)\">It\226\128\153s too dark in here...</font></i>",
	["Astral"] = "In the distant expanse of space, tiny stars emitting faint light come together to form a unified existence. These stars, embracing each other as they move in harmony, serve as the final puzzle pieces completing the beauty of the universe.",
	["Gravitational"] = "The irregularities of gravity incomprehensible to humans. It is thought to stem from the same material comprising the <b>mysterious <font color=\"rgb(71,97,230)\">Great Attractor</font></b>.",
	["Virtual"] = "An advanced <font color=\"rgb(68,174,255)\">hologram</font> device created by an unnamed civilization.",
	["Poseidon"] = "It has been shaped as a creature that once ruled the <font color=\"rgb(30,124,228)\">ocean</font> long ago. \nIt always maintains its posture, and all sea creatures are loyal to it. Except, <b><font color=\"rgb(17,13,97)\"><stroke color=\"rgb(39,29,223)\" thickness=\"1\" transparency=\"0\">one</stroke></font></b>.",
	["Galaxy"] = "It comes from an <b>unbelievably vast <font color=\"rgb(66,57,228)\">space</font></b> itself.",
	["Hades"] = "It has been shaped as the ruler of <font color=\"rgb(228,54,14)\">hell</font>, a long time ago. Though not replicated perfectly, it still remains cruel and callous.",
	["Starscourge"] = "When the stars aligned.. \nthe brightest starlights gathered to form <font color=\"rgb(230,67,102)\">this</font>.",
	["Sailor"] = "No one knows when this rusted fishing boat started its sail \nall that is known is that it is continuously advancing towards vast, <font color=\"rgb(74,94,93)\">rough waters</font>.",
	["Chromatic"] = "Yeah! Feel my <b>unstoppable beats</b>!!",
	["Ethereal"] = "In a country where the vast majority of people attend church, \nthere is a deep-rooted belief in powers, either from <b>\227\128\142</b><font color=\"rgb(128, 225, 255)\">God</font><b>\227\128\143</b> or from the \226\128\152<font color=\"rgb(67,63,63)\">dark side</font>\226\128\153. \nTheir god, is believed a spirit or being that has great power, strength, knowledge, etc., and that can affect nature and the lives of people. Someone will get this, and be an absolute and <font color=\"rgb(78,82,113)\">powerful being</font>...",
	["Matrix"] = "No one can see, hear or touch this; perhaps, \n\n<i>it might not even be <font color=\"rgb(32,230,138)\">real</font>.</i>",
	["Overture"] = "Inexorably, \n<font color=\"rgb(18,77,249)\">time</font> flows forward cruelly. \nIt cannot be stopped, or changed in direction. \n<i>Perhaps <font color=\"rgb(18,77,249)\">time</font> is a concept that exists in a dimension higher than the one we live in?</i>",
	["Impeached"] = "<font color=\"rgb(168,21,241)\"><b><stroke color=\"rgb(90,23,91)\" thickness=\"1\" transparency=\"0\">Violet</stroke></b></font> \nthe color symbolising royalty\nEmperor is one that illuminated the world, one that was the greatest leader ever, and one that architected its own downfall.\n\n<i>What\226\128\153s left for this <font color=\"rgb(168,21,241)\"><stroke color=\"rgb(90,23,91)\" thickness=\"1\" transparency=\"0\">fallen ruler</stroke></font>?</i>",
	["Oppression"] = "It was powerful and unstable enough to cause flaws in this world. \nThe authorities of the world gathered their strength to oppose it, but they failed. \nIts power grew steadily, until finally facing the <b>\227\128\142</b><font color=\"rgb(128, 225, 255)\">God</font><b>\227\128\143</b>, but in the face of the <b>\227\128\142</b><font color=\"rgb(128, 225, 255)\">God\'s</font><b>\227\128\143</b> unprecedented might, it was annihilated in an instant.\n\n<i>But is this truly the end for <font color=\"rgb(159,155,145)\">it</font></i>?",
	["Archangel"] = "The most pure, beautiful, and holy being, in the <font color=\"rgb(243,255,176)\">mythology</font>",
	["BLOODLUST"] = "This doesn\226\128\153t represent anything 0erior like a vampire or something, but rather <font color=\"rgb(146,15,15)\"><stroke color=\"rgb(208,39,39)\" thickness=\"1\" transparency=\"0.5\">never-ending thirst for blood</stroke></font> itself. \nAs the sentence depicts, it shows obsession\226\128\147almost to the point of insanity, for <font color=\"rgb(146,15,15)\"><stroke color=\"rgb(208,39,39)\" thickness=\"1\" transparency=\"0.5\">blood</stroke></font>..",
	["AbyssalHunter"] = "An <b><font color=\"rgb(17,13,97)\"><stroke color=\"rgb(39,29,223)\" thickness=\"1\" transparency=\"0\">unknown hunter</stroke></font></b>, slaughtering deep sea creatures mercilessly and roaming around the trenches.",
	["GARGANTUA"] = "<font color=\"rgb(0,0,0)\"><b><stroke color=\"rgb(185,102,40)\" thickness=\"1\" transparency=\"0\">Black-Hole</stroke></b></font> \nThe endless craving and void.\n\nThis colossal predator\'s size is so immense that it\'s immeasurable, capable of swallowing even <font color=\"rgb(66,57,228)\">galaxies</font> \0d there is nothing in physics stronger than it. \n\nIt has existed since the beginning of the universe \n<i>even now, it continues to devour everything that enters its domain, relentlessly moving forward.</i>",
	["Sovereign"] = "Look at this <font color=\"rgb(101,162,255)\"><b>Shining Figure</b></font><br/><br/><font color=\"rgb(101,162,255)\"><stroke color=\"#FFE08D\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\"><b>Sovereign</b></stroke></font>, revered as the most <font color=\"rgb(0,0,0)\"><b><stroke color=\"#FFE08D\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">Glorious</stroke></b></font> and <font color=\"rgb(0,0,0)\"><b><stroke color=\"#B38DFF\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">Magnificent</stroke></b></font> being among all rulers in history.<br/>He sought only <font color=\"rgb(255,213,84)\"><b>Pure Justice</b></font> and order, dedicating his life to achieving <font color=\"rgb(84,255,164)\"><b>Eternal Peace</b></font> in the world, but by <font color=\"rgb(0,0,0)\"><b><stroke color=\"#82009E\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">Evil</stroke></b></font> he was... <font color=\"rgb(0,0,0)\"><b><stroke color=\"#900000\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">[CENSORED]</stroke></b></font>",
	["Eclipse"] = "Some refer to this as a miracle, while others call it a disaster... \n\nwell, although it\'s merely a celestial event where the <font color=\"rgb(97,87,153)\">Moon</font> obscures the <font color=\"rgb(239,196,90)\">Sun</font>.",
	["Memory"] = "This is considered a follower of <font color=\"rgb(9,9,9)\"><stroke color=\"#BD00FF\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.25\"><b>Oblivion</b></stroke></font>, or a mere speck of existence by its 0luence. <br/><br/>It does not engage in any actions,<br/>but its mere presence is <font color=\"rgb(115,0,13)\"><b>Extremely Deadly</b></font> as it can strip away the will of both living and non-living things without distinguishing between them.<br/><br/>If you have encountered it...<br/><br/>No, it\'s already <font color=\"rgb(255,0,99)\"><b>Too Late</b></font>.",
	["Oblivion"] = "Apocalyptic weapon <font color=\"rgb(255,0,99)\"><b>Abomination</b></font> . . .<br/>Lord of <font color=\"rgb(111,55,205)\"><b>Futile Memories</b></font> . . .<br/><font color=\"rgb(0,0,0)\"><b><stroke color=\"rgb(255,0,69)\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">PURE EVIL . . .</stroke></b></font><br/><br/>Its sole <font color=\"rgb(255,0,69)\"><b>Purpose</b></font> is the downfall of the world, Sol.<br/><br/><font color=\"rgb(66,42,48)\">[More of the story will be revealed in the future.]</font>",
	["Blossom"] = "Like a blooming flower bud..",
	["Sol"] = "<font color=\"rgb(128, 225, 255)\">This is called the worldview itself. It is stronger than everything in this world combined and has outstanding power. It is owned by one person who is at the top among the many engineers who created the world.</font>",
	["Therma"] = "A figure of light and heat, the epitome of energy that never meets the darkness, and in the darkest of moments, they did shine the brightest. Their thermal abilities were described to be comparable to the sparks of creation, Therma.",
	["LAYERS"] = "i want to beat this map ngl",
	["LUNATIC"] = "<font color=\"rgb(211, 34, 255)\">A dazzling, incomplete one</font> that has variable form. Anyone who encounter this becomes <font color=\"rgb(211, 34, 255)\">frantic.</font>",
	["Glitch"] = "<font color=\"rgb(20, 20, 20)\">\n\n\n.--  ....  .-  -  ..--..     -.  ---  --..--     ..  -  .----.  ...     .-.  ..  -..  ..  -.-.  ..-  .-..  ---  ..-  ...  .-.-.-     ..  -     ...  ....  ---  ..-  .-..  -..  -.  .----.  -     ....  .-  .--.  .--.  .  -.</font>",
	["samgong"] = "<font color=\"rgb(139,77,30)\" size=\"30\"><b>\237\145\184\236\137\172\236\137\173!! \235\191\161..\235\191\161.. \237\145\184\235\147\156\235\147\157...!! \235\191\140\235\165\180\235\165\180\235\165\181...! \235\191\140\236\153\128\236\149\132\236\149\132\236\149\133!!!!! \237\144\137!! \235\191\140\235\165\181...! \235\191\140\235\164\132\235\164\132\235\164\133...!!! \237\144\129\235\139\185\240\159\146\169</b></font>",
	["FindTheProbabilityOfThisAura"] = "an aura that doesn\'t exist in the world",
	["yuyo"] = "\234\176\156\236\163\189\236\157\180.",
	["Dynasty"] = "It is warm work; and this day may be the last to any of us at a moment. But mark you! I would not be elsewhere for thousands.",
	["Ruins"] = "Wrecked ruins of the gods; What could it be hiding?",
	["Symphony"] = "Empty.",
	["MatrixOverdrive"] = "Empty.",
	["Atlas"] = "Empty.",
	["Surfer"] = "Empty.",
	["Starfish"] = "Empty.",
	["StarRider"] = "Empty.",
	["ShardSurfer"] = "Empty.",
	["Watermelon"] = "Empty.",
	["APOSTOLOS"] = "Empty.",
	["Innovator"] = "Empty.",
	["Sirius"] = "Empty.",
	["Aviator"] = "Empty.",
	["Luminosity"] = "Empty.",
	["PUMP"] = "Empty.",
	["Vital"] = "Empty.",
	["Moonflower"] = "Empty.",
	["NIGHTMARE SKY"] = "Empty.",
	["InvertedSovereign"] = "<font color=\"rgb(0,0,0)\"><b><stroke color=\"#900000\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">]DEOSNEC[</stroke></b></font> ...he was <font color=\"rgb(0,0,0)\"><b><stroke color=\"#82009E\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">livE</stroke></b></font> yb tub ,dlrow eht ni <font color=\"rgb(84,255,164)\"><b>ecaeP lanrete</b></font> gniveihca ot efil sih gnitacided dna ,redro dna <font color=\"rgb(255,213,84)\"><b>ecitsuJ eruP</b></font> ylno thguos eH.<br/>yrotsih ni srelur lla gnoma <font color=\"rgb(0,0,0)\"><b><stroke color=\"#B38DFF\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">tnicifingiM</stroke></b></font> dna <font color=\"rgb(0,0,0)\"><b><stroke color=\"#FFE08D\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\">suoirolG</stroke></b></font> tsom eht sa derever ,<font color=\"rgb(101,162,255)\"><stroke color=\"#FFE08D\" joins=\"miter\" thickness=\"1.5\" transparency=\"0.1\"><b>ngierevoS</b></stroke></font><br/><br/><font color=\"rgb(101,162,255)\"><b>erugiF gninihS</b></font> siht ta kooL",
	[":smiro:"] = "SMIRO",
	["ImChica"] = "I'm Chica!",
	["Diamond"] = "minecraft",
	["Minimum"] = "Minimum from Fortune's End.",
	["ScaryCar"] = "Scary Car from Fortune's End."
}