-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgOEAQVDbG9uZQZQYXJlbnQIUG9zaXRpb24IUm90YXRpb24EU2l6ZQ5TaXplQ29uc3RyYWludAVJbWFnZRFJbWFnZVRyYW5zcGFyZW5jeQlUd2VlbkluZm8DbmV3BEVudW0LRWFzaW5nU3R5bGUFUXVhcnQGQ3JlYXRlBFBsYXkHQWRkSXRlbQ5DcmVhdGVQYXJ0aWNsZQdBZG9ybmVlB1ZlY3RvcjIDb25lD1Nwcml0ZVNpemVQaXhlbAtTcHJpdGVDb3VudAxTcHJpdGVDb3VudFgJRnJhbWVSYXRlCUZyYW1lVGltZQZMb29wZWQOQ3JlYXRlRmxpcGJvb2sEdGltZQRtYXRoBnJhbmRvbQhSZW1vdmluZwxHZXRBdHRyaWJ1dGUMU2V0QXR0cmlidXRlBVVEaW0yCWZyb21TY2FsZQNzaW4JSGVhcnRiZWF0BFdhaXQISW5zdGFuY2UKSW1hZ2VMYWJlbApSZWxhdGl2ZVhYFkJhY2tncm91bmRUcmFuc3BhcmVuY3kLQW5jaG9yUG9pbnQJY29yb3V0aW5lBHdyYXASQ3JlYXRlUGFydGljbGVFbWl0AAZzY3JpcHQJVGV4dExhYmVsDFdhaXRGb3JDaGlsZAZzdHJpbmcDc3ViBFRleHQEdGFzawR3YWl0EFRleHRUcmFuc3BhcmVuY3kKQ3JlYXRlVGV4dAdQbGF5U0ZYBldob29zaAZWb2x1bWUccmJ4YXNzZXRpZDovLzEyNDg2MjQ0NjkwNjQxMQpSZWxhdGl2ZVlZBlpJbmRleCtodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTEwNDY4NTU0MDA5K2h0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9MTM5MTEzMDY1NDEYcmJ4YXNzZXRpZDovLzE2OTI0NDM0Njg5CkNyZWF0ZU1hcmsYcmJ4YXNzZXRpZDovLzEwMzUyNTU5NTczCUNyZWF0ZUZvZytodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTE3NTQ0MjIyOTUyB0Rlc3Ryb3kJQ3JlYXRlRGViBVZhbHVlBFJpbmcKRGlzY29ubmVjdBdyYnhhc3NldGlkOi8vODAzMDc2MDMzOAVkZWZlchhyYnhhc3NldGlkOi8vMTU3MTA5NjA3NDUYcmJ4YXNzZXRpZDovLzE1MDExNDY4NjkwK2h0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9MTQ4MjAwNzg1NTcYcmJ4YXNzZXRpZDovLzEzNDE0MzkyNDk0A0JHTQZMaW5lYXIJQmFzZUdyb3VwDUN1dHNjZW5lQXNzZXQGQWRkVGFnDUdyYWRpZW50RnJhbWUEU3RhcgdDb25uZWN0BFF1YWQPRWFzaW5nRGlyZWN0aW9uBUluT3V0Ck9uZU1pbFBsdXMHQW1iaWVudAtFeHBvbmVudGlhbAJJbhhyYnhhc3NldGlkOi8vMTY5MjQ1OTUyMzQYcmJ4YXNzZXRpZDovLzEwMTc2NjMyNjk1B1Zpc2libGUFRnJhbWUGQ29sb3IzEEJhY2tncm91bmRDb2xvcjMFUmVhZHkRR3JvdXBUcmFuc3BhcmVuY3kEZ2FtZQxUd2VlblNlcnZpY2UKR2V0U2VydmljZQZEZWJyaXMKUnVuU2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdNb2R1bGVzAlVJB3JlcXVpcmUHU2NlbmVVSQZBc3NldHMIRmxpcGJvb2sJRmxpcGJvb2syCFBhcnRpY2xlCVNoYWtlU2l6ZQlTcGluU3BlZWQKU3ByaXRlQ2xpcBRQUkVQQVJJTkcgW0FFR0lTXS4uLhFQT1dFUiBMRVZFTDogMTAwJRtbREVNT0xJU0hFUl0gQ0hBUkdJTkcgVVAuLi4RUE9XRVJFRCBBTkQgUkVBRFkWUFJPVE9DT0wgQ09ERTogW0FFR0lTXRRQUk9UT0NPTCBOVU1CRVI6IDUwMRciVEhFIFNISUVMRCBPRiBUSEUgU0tZIgxGQUNFIFRIRSBHT0QRRkFDRSBUSEUgQ0FMQU1JVFkMRkFDRSBUSEUgU0tZCEFORCBSSVNFABERCgMAAAAy+woAALwKCjoAAAAAnwoCAjABCiQBAAAAMAMKOwIAAACQCwcDMAsKOAQAAAAwBAovBQAAADAGCswGAAAAMAAKqQcAAACQCwgDMAsKowgAAAD7CwEAUg0KAKQOCwAAKJCAUg8CAKQQDwAONMDAnw4DAuIPEAAwBQ8vBQAAAA4JAgCMEAEAZQABAIwQAAAwEA+jCAAAALwLC5YRAAAAnwsFArwLC+4SAAAAnwsCAfsLAgBSDQoAUg4CALwLC3gTAAAAnwsEAYIAAQAUAwEDAgMDAgAAAAAAAAAAAwQDBQMGAwcDCAMJAwoEACiQgAMLAwwDDQQONMDABQIFCAMOAw8DEAA1EQEYAAAAAAEAAQABAAABAAEAAQABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAE2AAAAABEKAwAAAEr7CgAAvAoKOgAAAACfCgICMAMKOwEAAACQCwcCMAsKOAMAAAAwBAovBAAAADAGCswFAAAAkAsIAjALCqMGAAAAMAAKqQcAAAD7CwEAUg0KAKQOCgAAJICA2BAMAlsPEAukEBAADzjQwJ8OAwLiDxEAMAUPLwQAAAAOCQIAjBABAGUAAQCMEAAAMBAPowYAAAC8CwuWEgAAAJ8LBQK8CwvuEwAAAJ8LAgH7DAIATQsM7wkAAACfCwECMAoLFBQAAACkDhkAAGBwgVsNDhY+DA0VMAwL/BoAAACMDBAAMAwLVxsAAACMDAQAMAwLuhwAAAAwAgswHQAAAIwMAQAwDAstHgAAAKkMAAAwDAu1HwAAALwMC+4TAAAAnwwCATABCiQgAAAAggABACEDAQMDAgAAAAAAAAAAAwQDBQMGAwgDBwMJAwoEACSAgAIAAAAAAAAwQAIAAAAAAADwPwMLAwwDDQQPONDABQIEBgMOAw8DEgIAAAAAAAAQQAIAAAAAAACQQAMTAxQEAGBwgQMVAxYDFwMYAxkDGgMCAEIbARgAAAAAAQABAAABAAEAAQAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQABAAAAAAABAAABAAABAAEAAAEAAAEAAAIAAUMAAAAADAAIAAAAWaQAAQAAAABAnwABAqQDBQAAEDCAjAQPAIwFFACfAwMCPgIDAkMBAAL7AgAADgJMAPsDAABNAgMkBgAAAA4CSACkAgEAAAAAQJ8CAQJ4AwEHfQMkAAIAAAD7AgAAbwQIALwCAhIJAAAAnwIDAisCHQD7AgAAbwQIAKkFAQC8AgIuCgAAAJ8CBAH7AgEA+wQAAPsFAgDiBgwApAcPAAA40ICMCAAAjAkAAJ8HAwIwBwYvCwAAALwCApYQAAAAnwIFArwCAu4RAAAAnwICAfsCAwD7BAAAbwUHALwCAngSAAAAnwIEAaQEAQAAAABAnwQBAiYDBABbAgMT+wMAAPsFBACkBg8AADjQgG8IFAD7CwUA7AoCC7sYCgKkCRYAAFQwgJ8JAgIJBwgJ+woGADkJCgAJCAIJnwYDAkMEBQYwBAM7FwAAAPsEBwBNAwT9GAAAALwDA/cZAAAAnwMCAUgAsv+CAAEAGgMcBAAAAEACAAAAAAAAJEADHQMeBAAQMIADAgIAAAAAAADgPwMfAyADIQMFBQELAyIDIwQAONCAAw4DDwMQAgAAAAAAAElAAuxRuB6F67E/AyQEAFQwgAMDAyUDJgBlAAEYAAAAAQAAAAAAAAIAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAgAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAA9wtmAAAAAAwDBQAAAGCkAwIAAAQAgG8EAwBSBQAAnwMDAqQEBQAABECAnwQBAjAEAy8GAAAAMAEDqQcAAACkBAsACiSAwDAEA8wJAAAAjAQBADAEAzoMAAAApAQPAAA40ICMBfH/jAYPAJ8EAwIwBAM4EAAAAKQEEgAABBCBbwUTAG8GEwCfBAMCMAQD6BQAAAD7BAAAUgYDAPsHAQDiCBUApAkXAABYQIBSCgIAUgsCAJ8JAwIwCQgvBgAAALwEBJYYAAAAnwQFArwEBO4ZAAAAnwQCAaQEFwAAWECApAYPAAA40ICMBwAAjAhkAJ8GAwI+BQYajAYBAJ8EAwKkBg8AADjQgIwHMgCMCEYAnwYDAqQIDwAAONCAjAkBAIwKAgCfCAMCDQgDABsAAICMB///ZQABAIwHAQAJBQYHpAcPAAA40ICMCAIAjAkFAJ8HAwI+BgccpAcfAAB40IHZCAAAEgADABICAAASAgIAEgIDABIABAASAAUAEgAGABICBACfBwICnwcBAYIAAQAgAycDCgQABACAAygDIgQABECAAwUDBwMLAwYDKQQKJIDAAyoDHQMeBAA40IADBAMTBAAEEIECAAAAAAAA4D8DKwUBBgMjBABYQIADDgMPAgAAAAAAAFlAAgAAAAAAAPA/AgAAAAAAQH9AAywDLQQAeNCBAQJZLgEYAAAAAAABAAAAAAEAAQAAAAEAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAA4BWgAAAAALAgQAAABE+wMAAIcCAwHwAgIAAAAAgIIAAQCkAwIAAAAQQG8FAwC8AwPTBAAAAJ8DAwK8AwM6BQAAAJ8DAgIwAAMkBgAAAKQECQAAIHCAbwUKAG8HCwCVCAEMCQYHCJ8EAwIwBAM7DQAAAIwGAQAcBAIAjAUBAKgEDwCMCQEANC0CBQkGAABSCAIAUgoGAKQHEAAAPOCAnwcEAjAHA/URAAAApAcUAABMIIFvCAoAnwcCAYsE8f+kBBQAAEwggYwFAgCfBAIB+wQBAFIGAwD7BwIA4ggWAIwJAQAwCQgkFQAAALwEBJYXAAAAnwQFArwEBO4YAAAAnwQCAfsEAwBSBgMAjAcCALwEBHgZAAAAnwQEAYIAAQAaAy8DMAQAABBAAzEDMgMBAwIDIgMjBAAgcIACexSuR+F6lD8CexSuR+F6pD8CAAAAAAAAAEADAwMzAzQEADzggAM1AzYDNwQATCCBAzgFARUDDgMPAxAAdjkBGAAAAgAAAgAAAAAAAAAAAQABAAAAAAAAAAACAAAAAQAAAAAAAAAAAAEAAAD+BQAAAAIAAAAAAAAAAAAAAAABAAAAAAABdwAAAAAOAgUAAAClAfsDAABNAgOvAAAAAG8DAQDiBAMA9QYFAZUFBgQwBQRLAgAAAJ8CAwGkAggAABxggG8DCQBSBAAAnwIDAqQDDAAALKCAbwQNAG8FDQCfAwMCMAMCLw4AAABvAw8AMAMCqRAAAACkAxQAE0gQwTADAswSAAAAjAMBADADAjoVAAAAMAECoxYAAACkAxgAABxwgW8EGQBvBRkAnwMDAjADAugaAAAApAMMAAAsoIBvBBkAbwUZAJ8DAwIwAwI7GwAAAIwDCgAwAwINHAAAAPsDAQBSBQIA+wYCAOIHHQCkCAwAACyggG8JHgBvCh4AnwgDAjAIBy8OAAAAjAgBADAIB6MWAAAAvAMDlh8AAACfAwUCvAMD7iAAAACfAwIB+wMDAFIFAgCMBgIAvAMDeCEAAACfAwQB+wMEAG8EIgBSBQAAbwYZAKQHDAAALKCAbwgZAG8JGQCfBwMCpAgMAAAsoIBvCSMAbwojAJ8IAwKkCQwAACyggG8KJABvCyQAnwkDAqQKFAATSBDBpAsnAACYUIKMDAAAjA1oAZ8LAwJvDCMAqQ0BAJ8DCwH7AwQAbwQoAFIFAABvBikApAcMAAAsoIBvCBkAbwkZAJ8HAwKkCAwAACyggG8JIwBvCiMAnwgDAqQJDAAALKCAbwoqAG8LKgCfCQMCpAoUABNIEMGkCycAAJhQgowMAACMDWgBnwsDAm8MIwCpDQEAnwMLAfsDBABvBCsAUgUAAG8GKQCkBwwAACyggG8IGQBvCRkAnwcDAqQIDAAALKCAbwkjAG8KIwCfCAMCpAkMAAAsoIBvCiwAbwssAJ8JAwKkChQAE0gQwaQLJwAAmFCCjAwAAIwNaAGfCwMCbwwjAKkNAQCfAwsBggABAC0DOgM7AzwFAQICMzMzMzMz0z8CAAAAAAAA8D8DJwMKBAAcYIADKAMiAyMEACyggAKamZmZmZnpPwMFAz0DBwMLAwYDPgQTSBDBAyoDCAMTBAAccIECAAAAAAAA4D8DKwMDAz8FAg4WAmZmZmZmZuY/Aw4DDwMQA0ACmpmZmZmZyT8CAAAAAAAA+D8DHQMeBACYUIIDQQIzMzMzMzPjPwIzMzMzMzPzPwNCAmZmZmZmZvY/AIoBQwEYAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAEAAAEAAAABAAABAAEAAAAAAAABAAAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABiwAAAAALAAgAAABQpAABAAAAAECfAAECpAMFAAAQMICMBBQAjAUeAJ8DAwI+AgMCQwEAAvsCAAAOAkMA+wMAAE0CAyQGAAAADgI/AKQCAQAAAABAnwIBAngDAQd9AyAAAgAAAPsCAABvBAgAvAICEgkAAACfAgMCKwIZAPsCAABvBAgAqQUBALwCAi4KAAAAnwIEAfsCAQD7BAAA+wUCAOIGDACMBwEAMAcGowsAAAC8AgKWDQAAAJ8CBQK8AgLuDgAAAJ8CAgH7AgMA+wQAAG8FBwC8AgJ4DwAAAJ8CBAGkBAEAAAAAQJ8EAQImAwQAWwIDEPsDAAD7BQQApAYTAABIEIH7CQUAOQgJAAkHAgj7CgYAOQkKAAkIAgmfBgMCQwQFBjAEAzsUAAAA+wQHAE0DBP0VAAAAvAMD9xYAAACfAwIBSAC7/4IAAQAXAxwEAAAAQAIAAAAAAAAkQAMdAx4EABAwgAMCAgAAAAAAAOA/Ax8DIAMhAwgFAQsDDgMPAxACAAAAAAAASUADIgMjBABIEIEDAwMlAyYAqgEAARgAAAABAAAAAAAAAgAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAIAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAD3C6sAAAAACgEFAAAAc6QBAgAABACAbwIDAFIDAACfAQMCpAIGAAAUQICMAwEAjAQBAJ8CAwIwAgEvBwAAAG8CCAAwAgGpCQAAAKQCDQAMLKDAMAIBzAsAAACMAgEAMAIBOg4AAACMAgEAMAIBow8AAACkAhIAAEQAgYwDAACMBGgBnwIDAjACATgTAAAApAIVAAAEQIFvAxYAbwQWAJ8CAwIwAgHoFwAAAPsCAABSBAEA+wUBAOIGGABvBxkAMAcGow8AAAC8AgKWGgAAAJ8CBQK8AgLuGwAAAJ8CAgGkAgYAABRAgKQEEgAARACBjAUAAIwGZACfBAMCPgMEHKQFEgAARACBjAYAAIwHZACfBQMCPgQFHJ8CAwKkBRIAAEQAgYwGAgCMBwUAnwUDAj4EBR2kBhIAAEQAgYwHAQCMCAIAnwYDAg0GAwAeAACAjAX//2UAAQCMBQEACQMEBaQGEgAARACBjAcCAIwIBQCfBgMCPgUGHaQHEgAARACBjAgBAIwJAgCfBwMCDQcDAB4AAICMBv//ZQABAIwGAQAJBAUGpAUhAACA8IHZBgAAEgABABICAAASAgIAEgIDABIAAgASAAMAEgAEABICBACfBQICnwUBAYIAAQAiAycDCgQABACAAygDIgMjBAAUQIADBQNEAwcDCwMGAykEDCygwAMqAwgDHQMeBABEAIEDBAMTBAAEQIECAAAAAAAA4D8DKwUBDwLNzMzMzMzsPwMOAw8CAAAAAAAAWUACAAAAAADAokACAAAAAAAA8D8DLAMtBACA8IEBBp0BRQEYAAAAAAABAAAAAAAAAQAAAQAAAAEAAAEAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAOAZ4AAAAACAAHAAAAI/sAAAAOACAA+wEAAE0AASQAAAAADgAcAKQBAgAAABBAnwEBAvsCAQAmAAEC+wEAAPsDAgCkBAUAABAwgPsGAwAJBQAG+wcEAAkGAAefBAMCQwIDBDACATsGAAAA+wEAAPsDBQD7BQYACQQABUMCAwQwAgE4BwAAAKQBCgAAJICAnwEBAUgA3v+CAAEACwMCAxwEAAAQQAMiAyMEABAwgAMDAwQDNgM3BAAkgIAA2QEAARgBAAAAAAABAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAABAAD7B9oAAAAAEAEDAAAAnAGkAgMAAAgQgIwDKACMBGQAnwIDAj4BAgCkAgYAABRAgKQEAwAACBCAjAUAAIwGZACfBAMCPgMEAKQFAwAACBCAjAYAAIwHZACfBQMCPgQFAJ8CAwKkAwMAAAgQgIwEAACMBWgBnwMDAqQFAwAACBCAjAb2/4wHCgCfBQMCPgQFAKQGAwAACBCAjAf2/4wICgCfBgMCPgUGAKQHAwAACBCAjAj2/4wJCgCfBwMCPgYHB/sHAAC8Bwc6CAAAAJ8HAgKkCAYAABRAgFIJAQBSCgEAnwgDAjAIBy8JAAAApAgNAAwsoMAwCAfMCwAAAIwIAQAwCAejDgAAAG8IDwAwCAepEAAAAPsIAQBSCgcApAsTAABIEIGMDAEAnwsCAuIMFABvDRUAMA0Mow4AAAC8CAiWFgAAAJ8IBQK8CAjuFwAAAJ8IAgGkCBkAAACAQZ8IAQL7CgIATQkK7xIAAACfCQECMAcJFBoAAACkDB8AAHjQgVsLDBw+CgsbMAoJ/CAAAACMCkAAMAoJVyEAAACMCggAMAoJuiIAAACMCg8AMAoJMCMAAACMCgEAMAoJLSQAAACpCgEAMAoJtSUAAAC8CgnuFwAAAJ8KAgEwAAckJgAAAKQKKQAAoHCC2QsAABIABwASAAgAEgACABIABAASAAUAEgADABIABgCfCgICnwoBAaQKLAAArKCCjAsCAJ8KAgH7CgEAUgwHAKQNEwAASBCBjA4BAJ8NAgLiDhQAjA8BADAPDqMOAAAAvAoKlhYAAACfCgUCvAoK7hcAAACfCgIBpAosAACsoIKMCwEAnwoCAbwKB1AtAAAAnwoCAYIAAQAuAgAAAAAAAFlAAx0DHgQACBCAAyIDIwQAFECAAgAAAAAAACRAAwEDBQMLAwYDPgQMLKDAAwgDRgMHAwkDCgQASBCBBQEOApqZmZmZmek/Aw4DDwMcBAAAgEEDEgIAAAAAAAAgQAIAAAAAAACQQAMTAxQEAHjQgQMVAxYDFwMYAxkDGgMCAywDLQQAoHCCAzYDNwQArKCCA0cBCLsBSAEYAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAACAAAAAAABAAAAAAABAAAAAAACAAAAAQAAAAAAAAEAAAABAAABAAABAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAEAAQAAAAAAAQAAAQAAAQAAAQAAAQAAAQAAAgACAAAAAAAAAAAAAAgCAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAABAAABvAAAAAALAQUAAAA++wIAAE0BAiQAAAAADgE1APsBAQBNAgE4AQAAAFsEAAL7BgIATQUG7AMAAAAJAwQFQwICAzACATgBAAAA+wIAAE0BAq4EAAAATQIBOAEAAABbAwAFJgICAzACATgBAAAA+wEBAKQDCAAAHGCAbwQJAG8FCQCfAwMCpAQIAAAcYICkBw0AADCwgIwInP+MCWQAnwcDAj4GBwr7CAMATQcI7AMAAAAJBQYHpAgNAAAwsICMCZz/jApkAJ8IAwI+BwgK+wkDAE0ICewDAAAACQYHCJ8EAwJDAgMEMAIBOw4AAACCAAEA+wEEALwBARoPAAAAnwECAYIAAQAQAwIDBAIAAAAAAABOQANJA0oCAAAAAACAQUADIgMjBAAcYIACAAAAAAAA4D8CAAAAAABAn0ADHQMeBAAwsIADAwNLAPkBAAEYAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAL6AAAAAAcAAwAAABb7AQAATQABJAAAAAAOABEA+wABAA4ADwD7AAIA+wEAAG8CAQCkBAUAABAwgIwFBQCMBhQAnwQDAj4DBAKfAAQBpAAIAAAcYIBvAQkAnwACAUgA6/+CAAEACgMCA0wCAAAAAABAf0ADHQMeBAAQMIADNgM3BAAcYIACmpmZmZmZqT8AjAIAARgAAAAAAQABAAAAAAAAAAAAAQAAAP0FDQEAAAAMAAMAAACxAfsBAABNAAEkAAAAAA4ArAD7AAEADgCqAKQAAwAACBCA+wECAG8CBAD7AwAAjAQeAKQFBwAAGFCAbwYIAG8HCACfBQMCpAYHAAAYUIBvBwkAbwgJAJ8GAwKkBwcAABhQgIwIAQCMCQEAnwcDAqQIDQAMLKDApAkQAAA84ICMCgAAjAtoAZ8JAwJvChEAqQsBAJ8ADAGkAAMAAAgQgPsBAgBvAhIA+wMAAIwEHgCkBQcAABhQgG8GCABvBwgAnwUDAqQGBwAAGFCAbwcJAG8ICQCfBgMCpAcHAAAYUICMCAEAjAkBAJ8HAwKkCA0ADCygwKQJEAAAPOCAjAoAAIwLaAGfCQMCbwoTAKkLAQCfAAwBpAADAAAIEID7AQIAbwIUAPsDAACMBB4ApAUHAAAYUIBvBggAbwcIAJ8FAwKkBgcAABhQgG8HCQBvCAkAnwYDAqQHBwAAGFCAjAgBAIwJAQCfBwMCpAgNAAwsoMCkCRAAADzggIwKAACMC2gBnwkDAm8KCACpCwEAnwAMAaQAAwAACBCA+wECAG8CFQD7AwAAjAQeAKQFBwAAGFCApAcQAAA84ICMCAAAjAlkAJ8HAwI+BgcWbwcXAJ8FAwKkBgcAABhQgG8HGABvCBgAnwYDAqQHBwAAGFCAjAgBAIwJAQCfBwMCpAgNAAwsoMCkCRAAADzggIwKAACMC2gBnwkDAm8KEwCpCwAAnwAMAaQAAwAACBCA+wECAG8CFQD7AwAAjAQeAKQFBwAAGFCApAcQAAA84ICMCAAAjAlkAJ8HAwI+BgcWbwcZAJ8FAwKkBgcAABhQgG8HGABvCBgAnwYDAqQHBwAAGFCAjAgBAIwJAQCfBwMCpAgNAAwsoMCkCRAAADzggIwKAACMC2gBnwkDAm8KEwCpCwAAnwAMAaQAGwAAaBCAbwETAJ8AAgFIAFD/ggABABwDAgM2A00EAAgQgANOAyIDIwQAGFCAAgAAAAAAAOA/ApqZmZmZmck/AwsDBgM+BAwsoMADHQMeBAA84IACZmZmZmZm5j8DTwKamZmZmZm5PwNQA1ECAAAAAAAAWUACMzMzMzMz8z8CMzMzMzMz4z8CmpmZmZmZyb8DNwQAaBCAAJQCAAEYAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAPgKFQEAAAADAAQAAAAU+wEAAE0AASQAAAAADgAPAPsAAQAOAA0A+wACAPsBAACfAAIBpAADAAAIEID7AQMA+wIAAJ8AAwGkAAUAABAQgG8BBgCfAAIBSADt/4IAAQAHAwIDNgNNBAAIEIADNwQAEBCAAgAAAAAAAOA/AKECAAEYAAAAAAEAAQAAAQAAAAABAAAA/AYiAQAAAAcABAAAABekAAIAAAQAgIwBAgCfAAIBjAIBAPsDAAAcAAMAjAEBAKgADQD7AwEADgMLAKQDBAAADACA+wQCAPsFAwBSBgIAnwMEAaQDAgAABACAbwQFAJ8DAgGLAPP/ggABAAYDNgM3BAAEAIADTQQADACAAjMzMzMzM9M/AKoCAAEYAAAAAAEAAAAAAQABAAAAAAABAAAA/QUrAQAAABMBDgAAAJcEqQEBAPsDAABNAgOvAAAAAKQEAgAAABBATQME9QMAAADiBAUAjAUAADAFBEsEAAAAnwIDAvsDAQBSBQIApAYIAAAcYICMBwMApAgMAAsokMCfBgMC4gcFAG8IDQAwCAdLBAAAALwDA5YOAAAAnwMFArwDA+4PAAAAnwMCAaQDAgAAABBAbwUQALwDA9MRAAAAnwMDArwDAzoSAAAAnwMCAm8GEwC8BANFFAAAAJ8EAwEwAAMkFQAAAG8GFgC8BAPTEQAAAJ8EAwJvBxcAvAUD0xEAAACfBQMCxgYAAPsIAgBNBwj9GAAAANkJAAASAAMAEgAFABICAwASAgQAEgEG/7wHB8cZAAAAnwcDAlIGBwD7BwEAUgkDAKQKCAAAHGCAbwsaAKQMHAAbKJDAnwoDAuILHgCMDAAAMAwLOh0AAAC8BweWDgAAAJ8HBQK8BwfuDwAAAJ8HAgH7BwEAUgkEAKQKCAAAHGCAbwsaAKQMHAAbKJDAnwoDAuILHgBvDB8AMAwLOh0AAAC8BweWDgAAAJ8HBQK8BwfuDwAAAJ8HAgH7BwEA+wkDAKQKCAAAHGCAjAsBAKQMIQAgKJDAnwoDAuILIwCMDAIAMAwL7CIAAAC8BweWDgAAAJ8HBQK8BwfuDwAAAJ8HAgH7BwEA+wkEAKQKCAAAHGCAbwsaAKQMIQAgKJDAnwoDAuILIwCMDAAAMAwL7CIAAAC8BweWDgAAAJ8HBQK8BwfuDwAAAJ8HAgH7BwEAUgkFAKQKCAAAHGCAjAsBAKQMIQAgKJDAnwoDAuILJQCkDCgAAJxggowNAQCMDgEAnwwDAjAMCy8kAAAAvAcHlg4AAACfBwUCvAcH7g8AAACfBwIB+wcBAE0JA64pAAAApAoIAAAcYICMCwMApAwhACAokMCkDSwAK6iQwIwOAACpDwAAjBABAJ8KBwLiCy4ApAwoAACcYIJvDS8Abw4vAJ8MAwIwDAsvJAAAAG8MGgAwDAujLQAAALwHB5YOAAAAnwcFArwHB+4PAAAAnwcCAaQHMgAAxACD2QgBABIAAwASAQH/EgIFAJ8HAgKfBwEBpAcyAADEAIPZCAIAEgADABIBAf8SAgYAnwcCAp8HAQGkBzIAAMQAg9kIAwASAAMAEgEB/xICBwASAggAnwcCAp8HAQGkBzIAAMQAg9kIBAASAgkAEgEB/xICCgASAAMAnwcCAp8HAQH7CAAATQcIrwAAAABvCDMAnwcCAfsIAABNBwivAAAAAG8INACfBwICpAg3AADYUINvCTgAnwgCAfsIAQBSCgUApAsIAAAcYICMDAYApA06ADkokMCkDjwAO6iQwJ8LBALiDCUApA0oAACcYIKMDgMAjA8DAJ8NAwIwDQwvJAAAALwICJYOAAAAnwgFArwICO4PAAAAnwgCAaQINwAA2FCDjAkEAJ8IAgH7CAsAUgkDAG8KDQCfCAMBpAg3AADYUIOMCQEAnwgCAfsICwBSCQMAjAoAAJ8IAwGkCDcAANhQg4wJAQCfCAIB+wgMAG8JPQBSCgMAbwsaAKQMKAAAnGCCbw0aAG8OGgCfDAMCpA0oAACcYIJvDj4Abw8+AJ8NAwKkDigAAJxggowPAgCMEAIAnw4DAqQPQQBA/JDApBBEAAAMIYSMEQAAjBJoAZ8QAwJvET4AqRIBAJ8ICwH7CAwAbwlFAFIKAwBvCw0ApAwoAACcYIJvDRoAbw4aAJ8MAwKkDSgAAJxggm8OPgBvDz4Anw0DAqQOKAAAnGCCbw9GAG8QRgCfDgMCpA9BAED8kMCkEEQAAAwhhIwRAACMEmgBnxADAm8RPgCpEgEAnwgLAfsIDABvCUcAUgoDAG8LDQCkDCgAAJxggm8NGgBvDhoAnwwDAqQNKAAAnGCCbw4+AG8PPgCfDQMCpA4oAACcYIJvD0gAbxBIAJ8OAwKkD0EAQPyQwKQQRAAADCGEjBEAAIwSaAGfEAMCbxE+AKkSAQCfCAsB+wgMAG8JSQBSCgMAjAsBAKQMKAAAnGCCbw0aAG8OGgCfDAMCpA0oAACcYIJvDj4Abw8+AJ8NAwKkDigAAJxggm8PSgBvEEoAnw4DAqQPQQBA/JDApBBEAAAMIYSMEQAAjBJoAZ8QAwJvET4AqRIBAJ8ICwH7CAwAbwlLAFIKAwBvC0wApAwoAACcYIJvDRoAbw4aAJ8MAwKkDSgAAJxggm8OPgBvDz4Anw0DAqQOKAAAnGCCjA8DAIwQAwCfDgMCpA9BAED8kMCkEEQAAAwhhIwRAACMEmgBnxADAm8RPgCpEgEAnwgLAakIAAAwCAWATQAAAIwIAQAwCAM6HQAAAKkBAACkCE8AABzghG8JUABSCgAAnwgDAqQJKAAAnGCCjAoBAIwLAQCfCQMCMAkILyQAAACkCVIAABwQhYwKAQCMCwEAjAwBAJ8JBAIwCQifUwAAAIwJBAAwCQgNVAAAAPsJAQBSCwgApAwIAAAcYICMDQEAnwwCAuINHgCMDgEAMA4NOh0AAAC8CQmWDgAAAJ8JBQK8CQnuDwAAAJ8JAgH7CQ0AUgsIAIwMAQC8CQl4VQAAAJ8JBAH7CgAATQkKrwAAAACkCwIAAAAQQE0KCy9WAAAA4gsFAG8MGgAwDAtLBAAAAJ8JAwG8CQdQVwAAAJ8JAgG8CQJQVwAAAJ8JAgGpCQAAMAkEgE0AAABNCQOuKQAAAKkKAAAwCgmATQAAAPsJAQBSCwMApAwIAAAcYICMDQMAnwwCAuINWQCMDgEAMA4NglgAAAC8CQmWDgAAAJ8JBQK8CQnuDwAAAJ8JAgH7CQ0AUgsDAIwMAwC8CQl4VQAAAJ8JBAG8CQYaWgAAAJ8JAgHBAQAAggABAFsDOgMwBAAAEEADUgM8BQEEAwkDCgQAHGCAAwsDDANTBAsokMACMzMzMzMz4z8DDgMPA1QDMgMBA1UDVgMCA1cDWAMlA1kCAAAAAAAA4D8DWgQbKJDAAyoFAR0CMzMzMzMz6z8DDQQgKJDAA0kFASIDBQUBJAMiAyMEAJxgggNKA1sDXAQrqJDAAwgFAiQtApqZmZmZmdk/AywDLQQAxACDA10DXgM2AzcEANhQgwLXo3A9CtcJQANfBDkokMADYAQ7qJDAA0ACmpmZmZmZyT8DBgM+BED8kMADHQMeBAAMIYQDQQIAAAAAAAAEQANCAmZmZmZmZgJAA2ECzczMzMzM/D8DYgKamZmZmZnxPwNjAycEABzghANkA2UEABwQhQNmAz8DEANnA0cDaAUBWANLBQoLDA0O6wEAARgAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAQAAAAEAAgAAAAEAAAACAQAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAYCAAAAAAAACwIAAAAAAAAABwIAAAAAAAAABwIAAAAAAQAAAAACAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAQAAAQIAAAAAAQAAAAAAAAEAAAAAAAAAAQAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAIAAAAAAAAAAAAAAAEAAAEAAAIAAAEAAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAIAAAEA7AAAAAAdAAABAgCrAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwJvBgcAvAQD0wgAAACfBAMCbwcJALwFBNMIAAAAnwUDAqQGCwAAAKBAbwkMALwHBdMIAAAAnwcDAm8JDQC8BwfTCAAAAJ8HAwCfBgACpAcPAAAA4EBvCRAAvAcH0wgAAACfBwMCpAgPAAAA4EBvChEAvAgI0wgAAACfCAMCpAkPAAAA4EBvCxIAvAkJ0wgAAACfCQMCpAoPAAAA4EBvDBMAvAoK0wgAAACfCgMCpAsPAAAA4EBvDRQAvAsL0wgAAACfCwMCpAwLAAAAoEBvDxUAvA0E0wgAAACfDQMAnwwAAv8NAAAPAAAAbw4WAG8PFwBvEBgAbxEZAG8SGgBvExcAbxQbAG8VHABvFh0AbxcXAG8YHgBvGR8AbxogAG8bFwBvHCEAxQ0OEAEAAACkDiQAAIwggm8PJQCkECkAKJxgwp8OAwKkDyQAAIwggm8QJQCkESkAKJxgwqQSLAArqGDCnw8EAqQQJAAAjCCCjBECAKQSKQAonGDCnxADAsARLQASAAkAEgAAABIAAQDAEi4AEgAHABIAAAASAAwAwBMvABIAAAASAA4AEgAPABIAAQASAAIAwBQwABIADQASAAAAEgAQABIAAQDAFTEAEgAGABIAAAASABAAEgABABIAEQDAFjIAEgAAABIADgASAA8AEgABABIAAgDAFzMAEgAIABIAAAASAAwAwBg0ABIABgASAAAAEgACABIACwASAAoAEgATABIAEgASABYAEgAXABIADQASABQAEgAVABIAEQASAAEAghgCADUDaQQAAABAA2oDawNsA20DbgNvAzIDcANxBAAAoEADcgNzAzAEAADgQAN0A3UDdgN3A3gDeQN6Ay8DewN8A30DfgN/A4ABA4EBA4IBA4MBA4QBAwkDCgQAjCCCAgAAAAAAAOA/AwsDDAMNBCicYMIDWwNgBCuoYMIGAAYBBgMGBAYFBgcGCQYPCAABAwQFBwkPAQABGAACAAAAAAABAAAAAAABAAAAAAABAAAAAAAFAAAAAQAAAAEAAAAAAAAAAAAAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAQAAAAAABAAAAAAAAAIAAQEBAQEBAQEBAQEBAQEBAAAFAAAAAAABAAAAAAAAAAIAAAAAAAQAAAANAAAAFwAAAAAAHQAAAAAUAAAAAAATAAAAAAAeAAAAMAAAAAAAAAAAAAAAAAAAAAEAAAAAEA==

-- Error occured while requesting the API, error:

--[[
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is temporarily unavailable</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /*<![CDATA[*/
            body {
                background-color: #fff;
                color: #000;
                font-size: 0.9em;
                font-family: sans-serif,helvetica;
                margin: 0;
                padding: 0;
            }
            :link {
                color: #c00;
            }
            :visited {
                color: #c00;
            }
            a:hover {
                color: #f50;
            }
            h1 {
                text-align: center;
                margin: 0;
                padding: 0.6em 2em 0.4em;
                background-color: #294172;
                color: #fff;
                font-weight: normal;
                font-size: 1.75em;
                border-bottom: 2px solid #000;
            }
            h1 strong {
                font-weight: bold;
                font-size: 1.5em;
            }
            h2 {
                text-align: center;
                background-color: #3C6EB4;
                font-size: 1.1em;
                font-weight: bold;
                color: #fff;
                margin: 0;
                padding: 0.5em;
                border-bottom: 2px solid #294172;
            }
            h3 {
                text-align: center;
                background-color: #ff0000;
                padding: 0.5em;
                color: #fff;
            }
            hr {
                display: none;
            }
            .content {
                padding: 1em 5em;
            }
            .alert {
                border: 2px solid #000;
            }

            img {
                border: 2px solid #fff;
                padding: 2px;
                margin: 2px;
            }
            a:hover img {
                border: 2px solid #294172;
            }
            .logos {
                margin: 1em;
                text-align: center;
            }
            /*]]>*/
        </style>
    </head>

    <body>
        <h1><strong>nginx error!</strong></h1>

        <div class="content">

            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>

            <div class="alert">
                <h2>Website Administrator</h2>
                <div class="content">
                    <p>Something has triggered an error on your
                    website.  This is the default error page for
                    <strong>nginx</strong> that is distributed with
                    Fedora.  It is located
                    <tt>/usr/share/nginx/html/50x.html</tt></p>

                    <p>You should customize this error page for your own
                    site or edit the <tt>error_page</tt> directive in
                    the <strong>nginx</strong> configuration file
                    <tt>/etc/nginx/nginx.conf</tt>.</p>

                </div>
            </div>

            <div class="logos">
                <a href="http://nginx.net/"><img
                    src="/nginx-logo.png"
                    alt="[ Powered by nginx ]"
                    width="121" height="32" /></a>

                <a href="http://fedoraproject.org/"><img 
                    src="/poweredby.png"
                    alt="[ Powered by Fedora ]" 
                    width="88" height="31" /></a>
            </div>
        </div>
    </body>
</html>

--]]